[package]
name = "dlx"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.1.0"
clap = { version = "3.1.18", optional = true, features = ["derive"] }

[features]
emu-cli = ["clap"]

[[bin]]
name = "emu"
required-features = ["emu-cli"]
